### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by avinashshenoy97** [grassknoted/CDAE4InfoExtraction#3]
Please fix the broken image links in the README

<img width="1010" alt="screenshot 2018-12-18 at 10 11 07 am" src="https://user-images.githubusercontent.com/14026001/50132506-6181b900-02ad-11e9-97d9-5b252ffe7089.png">

**Comment by akhil-reddy** [comment]
Resolved

**Comment by grassknoted** [comment]
Thanks for pointing this out @avinashshenoy97!

**Comment by grassknoted** [comment]
Issue #6 , shows that the error still exists. Please fix it @akhil-reddy .
